services:
  dev:
    image: ruby
    command: tail -f /dev/null
    volumes:
      - .:/usr/src/app

  greenplum:
    image: kevinmtrowbridge/gpdb-docker
    ports:
      - 5432:5432
      - 8123:8123
    volumes:
      - ./tmp/custdata:/home/gpadmin/gpfdist-data
      - ./db:/db
    command: sh /db/start.sh
