version: '3.9'

services:
  dev:
    image: ruby:2
    command: tail -f /dev/null
    volumes:
      - .:/usr/src/app

  greenplum:
    image: kevinmtrowbridge/gpdb-docker
    volumes:
      - ./tmp/custdata:/home/gpadmin/gpfdist-data
      - ./db:/db
    command: sh /db/start.sh
