version: "3"

services:
  cranium:
    build:
      context: .
      args:
        - https_proxy
        - http_proxy
    volumes:
      - gpfdist-init:/app/tmp/custdata
      - greenplum-init:/app/jenkins/docker

  greenplum:
    image: kevinmtrowbridge/gpdb-docker
    depends_on:
      - cranium
    volumes:
      - gpfdist-init:/home/gpadmin/gpfdist-data
      - greenplum-init:/docker-entrypoint-initdb.d
    command: sh /docker-entrypoint-initdb.d/initialize_greenplum.sh

volumes:
  gpfdist-init:
  greenplum-init:
